-- Run this once in an existing Supabase project that already has the older NLGEP schema.
-- It adds server-side AI chat history without changing the existing community-chat tables.

create table if not exists public.render_ai_chats (
  chat_id uuid primary key,
  user_id text not null,
  title text not null default 'New Chat',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists render_ai_chats_user_updated_idx
  on public.render_ai_chats(user_id, updated_at desc);

create table if not exists public.render_ai_chat_messages (
  message_id bigint generated by default as identity primary key,
  chat_id uuid not null references public.render_ai_chats(chat_id) on delete cascade,
  user_id text not null,
  role text not null check (role in ('user', 'assistant')),
  content text not null check (char_length(content) between 1 and 6000),
  created_at timestamptz not null default now()
);

create index if not exists render_ai_chat_messages_chat_created_idx
  on public.render_ai_chat_messages(chat_id, created_at asc, message_id asc);

create index if not exists render_ai_chat_messages_user_idx
  on public.render_ai_chat_messages(user_id, created_at desc);

alter table public.render_ai_chats enable row level security;
alter table public.render_ai_chat_messages enable row level security;

grant all privileges on table public.render_ai_chats to service_role;
grant all privileges on table public.render_ai_chat_messages to service_role;
grant all privileges on sequence public.render_ai_chat_messages_message_id_seq to service_role;

notify pgrst, 'reload schema';
