-- Render AI database schema
-- Run once in the Supabase SQL editor before using chat, usage, community chat, or files.

create table if not exists public.render_files (
  id bigint generated by default as identity primary key,
  user_id text not null,
  path text not null unique,
  filename text not null,
  content_type text not null default 'application/octet-stream',
  size bigint not null check (size > 0),
  created_at timestamptz not null default now()
);

create index if not exists render_files_user_created_idx
  on public.render_files(user_id, created_at desc);

create table if not exists public.render_users (
  user_id text primary key,
  first_seen timestamptz not null default now(),
  last_seen timestamptz not null default now()
);

create index if not exists render_users_last_seen_idx
  on public.render_users(last_seen desc);

create table if not exists public.render_usage (
  id bigint generated by default as identity primary key,
  user_id text not null,
  provider text not null,
  feature text not null,
  model text,
  units integer not null default 1 check (units > 0),
  created_at timestamptz not null default now()
);

create index if not exists render_usage_provider_created_idx
  on public.render_usage(provider, created_at desc);

create index if not exists render_usage_user_created_idx
  on public.render_usage(user_id, created_at desc);

create index if not exists render_usage_user_provider_created_idx
  on public.render_usage(user_id, provider, created_at desc);

create table if not exists public.chat_users (
  user_id text primary key,
  username text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.chat_sessions (
  session_id text primary key,
  user_id text not null,
  username text not null,
  expires_at timestamptz not null,
  last_seen timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists chat_sessions_user_idx
  on public.chat_sessions(user_id);

create index if not exists chat_sessions_expires_idx
  on public.chat_sessions(expires_at);

create table if not exists public.chat_messages (
  message_id bigint generated by default as identity primary key,
  user_id text not null,
  username text not null,
  content text not null check (char_length(content) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists chat_messages_created_idx
  on public.chat_messages(created_at desc);

-- Private server-side tables. The app uses the Supabase service_role key.
alter table public.render_users enable row level security;
alter table public.render_usage enable row level security;
alter table public.chat_users enable row level security;
alter table public.chat_sessions enable row level security;
alter table public.chat_messages enable row level security;
alter table public.render_files enable row level security;

grant all privileges on table public.render_users to service_role;
grant all privileges on table public.render_usage to service_role;
grant all privileges on table public.chat_users to service_role;
grant all privileges on table public.chat_sessions to service_role;
grant all privileges on table public.chat_messages to service_role;
grant all privileges on table public.render_files to service_role;

grant all privileges on sequence public.render_usage_id_seq to service_role;
grant all privileges on sequence public.chat_messages_message_id_seq to service_role;
grant all privileges on sequence public.render_files_id_seq to service_role;

notify pgrst, 'reload schema';

-- Saved NLGEP AI conversations: up to 3 chats per user, with 5 messages kept per chat.
create table if not exists public.render_ai_chats (
  chat_id uuid primary key,
  user_id text not null,
  title text not null default 'New Chat',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists render_ai_chats_user_updated_idx
  on public.render_ai_chats(user_id, updated_at desc);

create table if not exists public.render_ai_chat_messages (
  message_id bigint generated by default as identity primary key,
  chat_id uuid not null references public.render_ai_chats(chat_id) on delete cascade,
  user_id text not null,
  role text not null check (role in ('user', 'assistant')),
  content text not null check (char_length(content) between 1 and 6000),
  created_at timestamptz not null default now()
);

create index if not exists render_ai_chat_messages_chat_created_idx
  on public.render_ai_chat_messages(chat_id, created_at asc, message_id asc);

create index if not exists render_ai_chat_messages_user_idx
  on public.render_ai_chat_messages(user_id, created_at desc);

alter table public.render_ai_chats enable row level security;
alter table public.render_ai_chat_messages enable row level security;

grant all privileges on table public.render_ai_chats to service_role;
grant all privileges on table public.render_ai_chat_messages to service_role;
grant all privileges on sequence public.render_ai_chat_messages_message_id_seq to service_role;

notify pgrst, 'reload schema';
